## Laboratorio 

### Tarea 4. Elementos básicos de Numpy

1. Supón que los nodos son los hashtag de todos los Twitter que se emiten en México en un cierto día. El peso de un enlace entre dos nodos de una red pude medir la proximidad entre esos dos nodos. ¿Cómo establecerías los pesos del enlace entre hashtags?

```Apelaría al criterio de coocurrencia, por lo que dos nodos (hashtags) tienden a ser cercanos cuando se presentan de manera muy frecuente en forma conjunta. Esto indicadiría que esas pequeñas narrativas comparten algún interés en común que sus autores quieren promover```


2. Crea un arreglo con tres elementos y obtén con la función del seno() de Numpy los valores correspondientes, los cuales deben ser almacenados en otro vector para ser impresos. Realiza la misma operación, pero por un camino largo. Ejecuta un loop en el que cada uno de los elementos del arreglo inicial es transformado con el seno()

In [1]:
import numpy as np
z = np.array([1, 2, 3])
sin_z = np.sin(z)
print(sin_z)

n = len(z)
y = np.zeros(n)
for i in range(n):
    y[i] = np.sin(z[i])
print(y)

[0.84147098 0.90929743 0.14112001]
[0.84147098 0.90929743 0.14112001]


3. Considera un polinomio de orden N. Escribe un programa con arreglos y métodos de Numpy.Implementa una función en la que se use el método cumprod(). Invoca a la función asignando un valor a la variable (x) y los coeficientes asociados del polinomio correspondiente (Ojo: si N = 2, debe haber tres coeficientes ya que hay un término constante). Estos coeficientes deben formar parte de un arreglo. Imprime el valor numérico de la función polinómica. Con el método de Numpy para la creación y evaluación de polinomios np.poly1d checa que el cálculo anterior sea el correcto. 

In [2]:
def p(x, coef):
     X = np.ones_like(coef)
     X[1:] = x           # se le pone el valor de x a todos los elementos menos el 1 inicial
     y = np.cumprod(X)   # y = [1, x, x**2,...],  se van acumulando multiplicaciones de x
     poli_x =coef @ y    # se multiplican los coeficientes con el vector  y
     return  poli_x        

x = 2
coef = np.array([2, 3, 4])
print(p(x, coef))
                               # Para checar que la operación es la correcta
q = np.poly1d(np.flip(coef))   # se usa flip ya que en este método el coeficiente inicial
                               # es el de x**N y el último el del término constante
print(q(x))                    # se evalua el polinomio en x

24
24


4. Crea una matriz (4 x 3) de números enteros generados aleatoriamente entre 0 y 10. Reemplaza los dos primeros vectores renglón con escalares = 7. Crea un nuevo arreglo (4 x 1) con puros unos y anéxalo con el método append() a la matriz anterior, imprime cada uno de los resultados parciales que vas generando.
  

In [3]:
mat1  = np.random.randint(0, 11, size=(4, 3)) #creas la matriz
print(mat1)
mat1[0:2] = 7 # Reemplazas con el 7
print(mat1)
tempo = np.ones((4, 1)) #matriz de unos
print (tempo)
mat2 = np.append(mat1,tempo, axis = 1) # pegas las matrices 
print (mat2)

[[ 0  8  8]
 [ 4  4  2]
 [ 6  6  1]
 [ 4 10  3]]
[[ 7  7  7]
 [ 7  7  7]
 [ 6  6  1]
 [ 4 10  3]]
[[1.]
 [1.]
 [1.]
 [1.]]
[[ 7.  7.  7.  1.]
 [ 7.  7.  7.  1.]
 [ 6.  6.  1.  1.]
 [ 4. 10.  3.  1.]]


### Tarea 5

1. Explicar cómo en una red real se puede saber si se presentan las siguientes propiedades: trayectorias cortas, aglutinamiento, y jerarquía en los grados
```Se compara la red real con una red aleatoria equivalente (número similar de nodos) y se checan las métricas de 'average path length' y 'average clustering' para saber que tan parecidas son, mientras que para saber si es jerárquicas se calcula 
la presencia de la 'power law' ```

2. Explicar por qué la red jerárquica de Barabasi es resiliente ante fallas aleatorias en los nodos



``` 
Porqué los nodos con muchos nodos son muy poco frecuentes y, por lo tanto, es raro que puedan presentar fallas. Al haber redundancia en las trayectorias es posible que un nodo fallido (con pocos vínculos y más frecuentes) no perturbe el acceso a un nodo desde otro nodo
```

3. Considera el siguiente diccionario:   
``` data = {'year': [2010, 2011, 2012, 2010, 2011, 2012, 2010, 2011, 2012],
             'team': ['FCBarcelona', 'FCBarcelona', 'FCBarcelona', 'RMadrid', 'RMadrid',      	    
                            'RMadrid', 'ValenciaCF', 'ValenciaCF', 'ValenciaCF'],
               'wins':   [30, 28, 32, 29, 32, 26, 21, 17, 19],
              'draws':  [6, 7, 4, 5, 4, 7, 8, 10, 8],
                'losses': [2, 3, 2, 4, 2, 5, 9, 11, 11] }
Escribe un script en el que muestres las siguientes instrucciones
i. Crear una estructura tabular con pandas
ii. Que se observen tan solo los tres primeros renglones de la tabla
iii. Que se observen los últimos cuatro renglones de la tabla 
iv. Que muestre estadísticas descriptivas
v. Que muestre los 'wins' de cada equipo
vi. Que muestre los renglones que están entre las posiciones 3 y 6 
vii. Que muestre una submatrix entre las posiciones 2 y 8 para 'team' y 'draws' 
viii. Que elija a todos los equipos que han obtenido más de 25 victorias
ix. Obtener los valores máximos de cada columna 
x. Obtener el valor mínimo de 'wins'
xi. Elevar al cuadrado el número que corresponde a 'draws' con una función anónima (lambda)
xii. Crear una nueva columna de'penalties' sin información disponible
xiii. Eliminar la columna de penalties para siempre.
xiv. Cambiar los valores de 'wins', 'draws' y 'losses' para ValenciaCF por NaN
xv. Cambiar el nombre de ValenciaCF por el de Sevilla.
```

In [68]:
import pandas as pd
import numpy as np
data = {'year': [2010, 2011, 2012, 2010, 2011, 2012, 2010, 2011, 2012],
        'team': ['FCBarcelona', 'FCBarcelona', 'FCBarcelona', 'RMadrid', 'RMadrid', 'RMadrid', 'ValenciaCF',
                 'ValenciaCF', 'ValenciaCF'],
        'wins':   [30, 28, 32, 29, 32, 26, 21, 17, 19],
        'draws':  [6, 7, 4, 5, 4, 7, 8, 10, 8],
        'losses': [2, 3, 2, 4, 2, 5, 9, 11, 11]
        }
fut = pd.DataFrame(
    data, columns=['year', 'team', 'wins', 'draws', 'losses']) #Creamos estructura
print(fut)
print(fut.head(3)) #primeros tres
print(fut.tail(4)) #ultimos cuatro
print(fut.describe()) # estadisticas descriptivas
print(fut['wins']) # se mustran los wins
fut[3:7] # se muestren los renglones entre el 3 y 6
fut.iloc[2:9, [1 , 3]] # submatriz para team y draws
fut[fut['wins']> 25] # equipos con mas de 25 victorias
fut.max(axis = 0) # maximos de cada columna
fut['wins'].min() # minimo wins
fut['draws'].apply(lambda d: d**2) # elevan al cuadrado draws
fut['penalties'] = np.nan # creamos columna nueva
fut.drop('penalties', inplace=True, axis = 1) # eliminanos
fut
fut.iloc[6:9, 2:] = np.nan # para el valencia por nan
fut
fut['wins'] = [30, 28, 32, 29, 32, 26, 21, 17, 19]
fut
fut.iloc[ :  , 2: ]
fut.iloc[6: , 1 ] = 'Sevilla' #cambiamos nombre 
fut


   year         team  wins  draws  losses
0  2010  FCBarcelona    30      6       2
1  2011  FCBarcelona    28      7       3
2  2012  FCBarcelona    32      4       2
3  2010      RMadrid    29      5       4
4  2011      RMadrid    32      4       2
5  2012      RMadrid    26      7       5
6  2010   ValenciaCF    21      8       9
7  2011   ValenciaCF    17     10      11
8  2012   ValenciaCF    19      8      11
   year         team  wins  draws  losses
0  2010  FCBarcelona    30      6       2
1  2011  FCBarcelona    28      7       3
2  2012  FCBarcelona    32      4       2
   year        team  wins  draws  losses
5  2012     RMadrid    26      7       5
6  2010  ValenciaCF    21      8       9
7  2011  ValenciaCF    17     10      11
8  2012  ValenciaCF    19      8      11
              year       wins      draws     losses
count     9.000000   9.000000   9.000000   9.000000
mean   2011.000000  26.000000   6.555556   5.444444
std       0.866025   5.656854   2.006932   3.844188

year         team  wins  draws  losses
0  2010  FCBarcelona    30    6.0     2.0
1  2011  FCBarcelona    28    7.0     3.0
2  2012  FCBarcelona    32    4.0     2.0
3  2010      RMadrid    29    5.0     4.0
4  2011      RMadrid    32    4.0     2.0
5  2012      RMadrid    26    7.0     5.0
6  2010      Sevilla    21    NaN     NaN
7  2011      Sevilla    17    NaN     NaN
8  2012      Sevilla    19    NaN     NaN

### Ejercicios 

1.	Para calcular la diferencia entre los valores máximo y mínimo de una matriz dada a lo largo del segundo eje.

In [12]:
x = np.arange(12).reshape((2, 6)) #Hacemos matriz
print("\narray original:")
print(x)
r1 = np.ptp(x, 1) #Rango de valores max y min por filas 
r2 = np.amax(x, 1) - np.amin(x, 1) # A manita
assert np.allclose(r1, r2) # regresa verdadero si se parecen 
print("\ndiferencia:")
print(r1)


array original:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

diferencia:
[5 5]


2.	Calcular el percentil 80 para todos los elementos en una matriz dada a lo largo del segundo eje.

In [13]:
x = np.arange(12).reshape((2, 6)) # Matriz
print("\narray:") 
print(x)
r1 = np.percentile(x, 80, 1) # Regresa el percentil 80 de cada fila
print("\n80th percentil:")
print(r1)


array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

80th percentil:
[ 4. 10.]


3.	Arreglo de cinco numeros de una distribucion normal

In [9]:
x = np.random.normal(size=5) # Hacemos el arreglo
print(x)

[-1.44426985  0.42452392 -1.95096263  0.07660879  0.10817319]


4.	Escriba un programa NumPy para crear una matriz aleatoria de 10x4 y extraiga las primeras cinco filas de la matriz y guárdelas en una variable

In [69]:
x = np.random.rand(10, 4) #Matriz
print("Array original: ")
print(x)
y= x[:5, :] #primeras 5 filas
print("Primeras cinco filas:")
print(y)

Array original: 
[[0.58712164 0.31584842 0.49368451 0.81022738]
 [0.1040315  0.37364839 0.61330667 0.94164464]
 [0.13144945 0.68286769 0.38245483 0.43551081]
 [0.38961887 0.9872654  0.63620756 0.93301325]
 [0.85814014 0.84504513 0.13410813 0.64683506]
 [0.95510797 0.04935348 0.94883209 0.13359652]
 [0.07508103 0.8495176  0.44173577 0.63687732]
 [0.45823616 0.31320878 0.99211992 0.3695401 ]
 [0.3041919  0.8964926  0.31566894 0.58192753]
 [0.54636522 0.46209715 0.51320745 0.2720081 ]]
Primeras cinco filas:
[[0.58712164 0.31584842 0.49368451 0.81022738]
 [0.1040315  0.37364839 0.61330667 0.94164464]
 [0.13144945 0.68286769 0.38245483 0.43551081]
 [0.38961887 0.9872654  0.63620756 0.93301325]
 [0.85814014 0.84504513 0.13410813 0.64683506]]


5.	Escriba un programa NumPy para normalizar una matriz aleatoria de 3x3

In [70]:
x= np.random.random((3,3)) # Matriz
print("Original:")
print(x)
xmax = x.max()
xmin =  x.min() #Sacamos maximo y minimo
x = (x - xmin)/(xmax - xmin) #A cada elemento le resta el minimo y lo divide entre la diferencia
print("Normalizada:")
print(x)

Original:
[[0.81832302 0.90839728 0.94310371]
 [0.27853204 0.53234482 0.93973026]
 [0.15618962 0.29738403 0.68154056]]
Normalizada:
[[0.84143035 0.95589553 1.        ]
 [0.15547113 0.47801304 0.99571305]
 [0.         0.17942799 0.66760902]]


6.	Escriba un programa NumPy para crear un vector aleatorio de tamaño 10 y ordenarlo

In [71]:
x = np.random.random(10) # Creamos
print("Original:")
print(x)
x.sort() #Ordenamos
print("Ordenado:")
print(x)

Original:
[0.04773384 0.50875528 0.29372029 0.85916763 0.22733429 0.86474715
 0.04194697 0.91005553 0.03887742 0.09744359]
Ordenado:
[0.03887742 0.04194697 0.04773384 0.09744359 0.22733429 0.29372029
 0.50875528 0.85916763 0.86474715 0.91005553]


7.	Escriba un programa NumPy para crear un vector aleatorio de tamaño 15 y reemplace el valor máximo por -1.


In [72]:
import numpy as np
x = np.random.random(15)
print("Original:")
print(x)
x[x.argmax()] = -1 #Agarramos el maximo 
print("reemplazando:")
print(x)

Original:
[0.33059389 0.63478182 0.9782475  0.48734747 0.40852773 0.25091902
 0.08964267 0.89123819 0.01134664 0.97079046 0.50814472 0.97542114
 0.79377717 0.10029941 0.38746401]
reemplazando:
[ 0.33059389  0.63478182 -1.          0.48734747  0.40852773  0.25091902
  0.08964267  0.89123819  0.01134664  0.97079046  0.50814472  0.97542114
  0.79377717  0.10029941  0.38746401]


### Repaso pandas

## DataFrames y Series

Las funcionalidades de `pandas` se basan en dos estructuras de datos fundamentales: *Series* y *DataFrames*.

Una `Series` es un objeto que contiene un `array` unidimensional de datos y un `array` de etiquetas, conocido como *índice*. Si no se especifica un índice o etiqueta, este se genera internamente como una secuencia ordenada de números enteros.

```python
s = pd.Series(data, index=index)
```

Un `DataFrame` es una estructura de datos que almacena datos de forma tabular, es decir, ordenada en filas y columnas etiquetadas. Cada fila (`row`) contiene una observación y cada columna (`column`) una variable. Un `DataFrame` acepta datos heterogéneos, es decir, variables pueden ser de distinto tipo (numérico, string, boolean, etc.). Además de contener datos, un `DataFrame` contiene el nombre de las variables y sus tipos, y métodos que permiten acceder y modificar los datos.

```python
s = pd.DataFrame(data, ...)
```

Las `Series` y `DataFrame` permiten representar datos 1D y 2D. Para representar datos con más dimensiones `pandas` posee otras estructuras de datos más complejas (en fase experimental), llamadas `Panel`, `Panel4D`, `PanelND`. Estas estructuras están fuera del alcance de este curso.

#### Creacion de series
Crear una Series con índices automáticos a partir de una lista

In [15]:
import pandas as pd
serie = pd.Series([1979, 1980, 1981, 1982])
serie

0    1979
1    1980
2    1981
3    1982
dtype: int64

Las `Series` poseen dos atributos: `values`  e `index`. El primero es un `numpy array` que almacena los datos, y el segundo es un objeto que contiene los índices.

In [16]:
serie.values

array([1979, 1980, 1981, 1982], dtype=int64)

In [17]:
serie.index

RangeIndex(start=0, stop=4, step=1)

Al crear una `Series` se puede definir explícitamente un `array` índice y pasarlo como argumento.

In [18]:
serie = pd.Series(data=[1979, 1980, 1981, 1982, 1983],
                  index=['carolina', 'martha', 'nicky', 'theresa', 'nicky'])
serie

carolina    1979
martha      1980
nicky       1981
theresa     1982
nicky       1983
dtype: int64

In [19]:
serie["carolina"]

1979

También se pueden crear `Series` a partir de diccionarios, `numpy arrays`, desde ficheros, etc.

In [20]:
np.random.randn(10)

array([ 0.07716925, -0.48063635, -0.86375154, -0.72121427,  0.20415092,
        1.38657575, -0.34668105, -0.48647024,  1.27858884, -0.63215079])

In [21]:
serie = pd.Series(np.random.randn(10))
serie

0    1.126677
1    0.546761
2    0.568334
3   -0.159193
4    0.063407
5    0.364563
6   -1.382410
7   -0.294524
8   -0.379617
9    0.623799
dtype: float64

In [22]:
dicc = {'cuadrado de {}'.format(i): i * i for i in range(11)}
print(dicc)

{'cuadrado de 0': 0, 'cuadrado de 1': 1, 'cuadrado de 2': 4, 'cuadrado de 3': 9, 'cuadrado de 4': 16, 'cuadrado de 5': 25, 'cuadrado de 6': 36, 'cuadrado de 7': 49, 'cuadrado de 8': 64, 'cuadrado de 9': 81, 'cuadrado de 10': 100}


In [23]:
serie_dicc = pd.Series(dicc)
serie_dicc

cuadrado de 0       0
cuadrado de 1       1
cuadrado de 2       4
cuadrado de 3       9
cuadrado de 4      16
cuadrado de 5      25
cuadrado de 6      36
cuadrado de 7      49
cuadrado de 8      64
cuadrado de 9      81
cuadrado de 10    100
dtype: int64

In [24]:
serie_dicc.values

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int64)

#### Acceso a datos en Series
El acceso a los datos se puede realizar mediante el índice categórico o el numérico que genera internamente Pandas

In [26]:
serie = pd.Series(data=[1979, 1980, 1981, 1982, 1983],
                  index=['carolina', 'martha', 'nicky', 'theresa', 'nicky'])
serie

carolina    1979
martha      1980
nicky       1981
theresa     1982
nicky       1983
dtype: int64

In [27]:
print(serie['martha']) #Mediante etiqueta

1980


In [28]:
print(serie[1]) #mediante indice interno numerico

1980


#### Métodos en Series


Para **añadir** nuevos elementos a una Series usamos el método `append`:

In [31]:
s1 = pd.Series(np.arange(10))
s2 = pd.Series(np.arange(10, 21))

s3 = s1.append(s2) #Mantiene indices
s3

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
0     10
1     11
2     12
3     13
4     14
5     15
6     16
7     17
8     18
9     19
10    20
dtype: int32

In [32]:
s3 = s1.append(s2, ignore_index=True) #indices nuevos
s3 

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
dtype: int32

El método pop devuelve y elimina de la serie original el valor del índice pasado

In [33]:
s4 = s1.pop(3)
print(s4)
print(s1)

3
0    0
1    1
2    2
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32


---
# Dataframes en Pandas

## Creación de Dataframes

A diferencia de `Series`, los `DataFrame` están diseñados para almacenar datos heterogéneos multivariables. Por ejemplo:

In [34]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
df = pd.DataFrame(data)
df

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [35]:
df.to_dict()

{'state': {0: 'Ohio', 1: 'Ohio', 2: 'Ohio', 3: 'Nevada', 4: 'Nevada'},
 'year': {0: 2000, 1: 2001, 2: 2002, 3: 2001, 4: 2002},
 'pop': {0: 1.5, 1: 1.7, 2: 3.6, 3: 2.4, 4: 2.9}}

In [36]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
df = pd.DataFrame(data, index = ["100", "101", "102", "103", "104"] )
df

state  year  pop
100    Ohio  2000  1.5
101    Ohio  2001  1.7
102    Ohio  2002  3.6
103  Nevada  2001  2.4
104  Nevada  2002  2.9

In [37]:
df.index

Index(['100', '101', '102', '103', '104'], dtype='object')

In [38]:
df.columns

Index(['state', 'year', 'pop'], dtype='object')

#### Acceso a datos en Dataframes
Se pueden extraer columnas de un `DataFrame` con la etiqueta de la columna (sólo si es un identificador Python válido)  usando notación tipo diccionario o como atributo del objeto. En ambos casos se obtiene un objeto tipo `Series`.

In [39]:
df['state']  # dict type

100      Ohio
101      Ohio
102      Ohio
103    Nevada
104    Nevada
Name: state, dtype: object

In [41]:
df[["state", "year"]] #Varias columnas

state  year
100    Ohio  2000
101    Ohio  2001
102    Ohio  2002
103  Nevada  2001
104  Nevada  2002

In [42]:
df.loc["100", "year"] #Acceder a un atributo

2000

In [43]:
df.loc["102", ["year", "pop"]]

year    2002
pop      3.6
Name: 102, dtype: object

In [44]:
df.iloc[1] #por indice

state    Ohio
year     2001
pop       1.7
Name: 101, dtype: object

### Datos ausentes (missing values)

La mayor parte de los datasets presentan registros con uno o varios campos cuya información está ausente (**missing values**), lo que puede generar problemas al intentar representar los datos, realizar ciertas operaciones o aplicarlo a un algoritmo. Es por eso que es necesario identificar y tratar esos valores ausentes. 

Las dos estrategias de tratamiento son el borrado o la asignación un valor determinado.

`Pandas` toma a los valores `NaN` y `None` como valores ausentes.

In [45]:
df = pd.DataFrame({'VarA': ['aa', None, 'cc',None],
                  'VarB': [20, 30, None,None],
                  'VarC': [1234, 3456, 6789,765],
                  'VarD': [1234, 888, None,None]
                 },
                 index=['Case1', 'Case2', 'Case3', 'Case4'])
df

VarA  VarB  VarC    VarD
Case1    aa  20.0  1234  1234.0
Case2  None  30.0  3456   888.0
Case3    cc   NaN  6789     NaN
Case4  None   NaN   765     NaN

In [46]:
df.isnull() #comprobar si tiene nan

VarA   VarB   VarC   VarD
Case1  False  False  False  False
Case2   True  False  False  False
Case3  False   True  False   True
Case4   True   True  False   True

In [47]:
df.isnull().values.any() # Nos indica si algun valor del dataframe es nulo

True

In [48]:
df.dropna() # Quita valores nan

VarA  VarB  VarC    VarD
Case1   aa  20.0  1234  1234.0

In [49]:
df.dropna(subset=['VarB']) # Indicamos columna

VarA  VarB  VarC    VarD
Case1    aa  20.0  1234  1234.0
Case2  None  30.0  3456   888.0

In [56]:
df.dropna(thresh=2) #numero minimo de nans por registro

VarA  VarB  VarC    VarD
Case1    aa  20.0  1234  1234.0
Case2  None  30.0  3456   888.0
Case3    cc   NaN  6789     NaN

In [57]:
df.fillna('new') #llenamos con otra cosa

VarA  VarB  VarC    VarD
Case1   aa  20.0  1234  1234.0
Case2  new  30.0  3456   888.0
Case3   cc   new  6789     new
Case4  new   new   765     new

### Ejercicios
Considere el siguiente diccionario `data` y lista de `index`

In [75]:
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


- a. Crea un DataFrame a partir del diccionario y los índices.
- b. Selecciona las columnas `animal`y `age`.
- c. Indique cuantos tipos distintos de animales hay.
- d. Indique cuantos animales hay de cada tipo.
- e. Muestre un resumen estadístico de todas las variables.

In [82]:
df = pd.DataFrame(data, index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
df
df.describe()

age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

In [59]:
raw_data = {'first_name': ['Jason', 'Mary', 'Tina', 'Jake', 'Amy','Anne'], 
        'last_name': ['Miller', 'Smith', 'Ali', 'Milner', 'Cooze','Lynn'], 
        'age': [42, np.nan, 36, 24, 73,'23'], 
        'sex': ['m', np.nan, 'f', 'm', 'f','f'], 
        'preTestScore': [4, np.nan, np.nan, 2, 3, np.nan],
        'postTestScore': [25, np.nan, np.nan, 62, 70, np.nan]}
df = pd.DataFrame(raw_data, columns = ['first_name', 'last_name', 'age', 'sex', 'preTestScore', 'postTestScore'])
df

first_name last_name  age  sex  preTestScore  postTestScore
0      Jason    Miller   42    m           4.0           25.0
1       Mary     Smith  NaN  NaN           NaN            NaN
2       Tina       Ali   36    f           NaN            NaN
3       Jake    Milner   24    m           2.0           62.0
4        Amy     Cooze   73    f           3.0           70.0
5       Anne      Lynn   23    f           NaN            NaN

- a. Determine que columna(s) tiene(n) el mayor número de NaNs.
- b. Elimine los registros con mayor número de nulos
- c. Complete la variable 'preTestScore' con el valor medio

Escriba un programa Pandas para calcular el mínimo, el percentil 25, la mediana, el 75 y el máximo de una serie dada.

In [60]:
num_state = np.random.RandomState(100) #Creamos 
num_series = pd.Series(num_state.normal(10, 4, 20)) # normal([loc, scale, size])	Draw random samples from a normal (Gaussian) distribution.
print("Original:")
print(num_series)
result = np.percentile(num_series, q=[0, 25, 50, 75, 100]) #Sacamos percentil
print("\nMinimo, 25th percentil, mediana, 75th, and maximo :")
print(result)

Original:
0      3.000938
1     11.370722
2     14.612143
3      8.990256
4     13.925283
5     12.056875
6     10.884719
7      5.719827
8      9.242017
9     11.020006
10     8.167892
11    11.740654
12     7.665620
13    13.267388
14    12.690883
15     9.582355
16     7.874878
17    14.118931
18     8.247458
19     5.526727
dtype: float64

Minimo, 25th percentil, mediana, 75th, and maximo :
[ 3.00093811  8.09463867 10.23353705 12.21537733 14.61214321]


Programa para mostrar el valor más frecuente en una serie dada y reemplazar todo lo demás como 'Otro' en la serie.

In [61]:
np.random.RandomState(100)
num_series = pd.Series(np.random.randint(1, 5, [15]))
print("OriginaL:")
print(num_series)
print("Top 2 Freq:", num_series.value_counts())
result = num_series[~num_series.isin(num_series.value_counts().index[:1])] = 'Other'
print(num_series)

OriginaL:
0     1
1     2
2     4
3     1
4     4
5     3
6     2
7     4
8     4
9     1
10    4
11    2
12    3
13    4
14    1
dtype: int32
Top 2 Freq: 4    6
1    4
2    3
3    2
dtype: int64
0     Other
1     Other
2         4
3     Other
4         4
5     Other
6     Other
7         4
8         4
9     Other
10        4
11    Other
12    Other
13        4
14    Other
dtype: object


Filtrar palabras de una serie dada que contienen al menos dos vocales

In [73]:
from collections import Counter
color_series = pd.Series(['Red', 'Green', 'Orange', 'Pink', 'Yellow', 'White'])
print("Original:")
print(color_series)
print("\nFiltrado:")
result = mask = color_series.map(lambda c: sum([Counter(c.lower()).get(i, 0) for i in list('aeiou')]) >= 2)
print(color_series[result])

Original:
0       Red
1     Green
2    Orange
3      Pink
4    Yellow
5     White
dtype: object

Filtrado:
1     Green
2    Orange
4    Yellow
5     White
dtype: object


Mostrar un resumen de la información básica sobre un DataFrame específico y sus datos.

In [63]:
exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("Resumen:")
print(df.info())

Summary of the basic information about this DataFrame and its data:
<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10 non-null     object 
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64  
 3   qualify   10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes
None


Seleccione las filas donde el número de intentos en el examen es inferior a 2 y la puntuación es superior a 15.

In [64]:
exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data , index=labels)
print("número de intentos en el examen inferior a 2 y la puntuación es superior a 15 :")
print(df[(df['attempts'] < 2) & (df['score'] > 15)]) 

número de intentos en el examen inferior a 2 y la puntuación es superior a 15 :
    name  score  attempts qualify
j  Jonas   19.0         1     yes


Reemplace todos los valores de NaN con cero en una columna de un marco de datos

In [65]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
df = pd.DataFrame(exam_data)
print("Original DataFrame")
print(df)
df =  df.fillna(0)
print("\nNew DataFrame replacing all NaN with 0:")
print(df)

Original DataFrame
        name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
3      James    NaN         3      no
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
7      Laura    NaN         1      no
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes

New DataFrame replacing all NaN with 0:
        name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
3      James    0.0         3      no
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
7      Laura    0.0         1      no
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes
