In [1]:
import numpy as np

## Ejercicio 1

Checar si un vector tiene un 0

In [9]:
vec_1 = np.array([0,1,3,4,5,0,10])

**Método 1:**

In [6]:
np.where(vec_1 == 0, True, False)

array([ True, False, False, False, False,  True, False])

**Método 2:**

In [8]:
if 0 in vec_1:
    print("Hay un 0")

Hay un 0


## Ejercicio 2

Eliminar elementos de un array 

In [26]:
def delete(vec,ind):
    return np.delete(vec, index)

In [30]:
vec_1 = np.array([1,2,3,4,5,6,7,8,9,10])
index = [0,1,2,3]
print("El vector original es: " + str(vec_1) + "\n")
print("Las entradas que borraremos son: " + str(index) + "\n")
print("El nuevo vector es: " + str(delete(vec_1,index)))

El vector original es: [ 1  2  3  4  5  6  7  8  9 10]

Las entradas que borraremos son: [0, 1, 2, 3]

El nuevo vector es: [ 5  6  7  8  9 10]


In [25]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
index = [2, 3, 6]

new_a = np.delete(a, index)
print(new_a)

[1 2 5 6 8 9]


## Ejercicio 3

Multiplicacion de dos matrices

In [23]:
np.random.seed(8)  
A = np.random.randint(11, size=(6, 7))
B = np.random.randint(11, size=(7, 3))
print(A)
print("\n")
print(B)

[[ 3  4  1  9  5 10  8]
 [ 3  8  0  5  1  3 10]
 [ 9  2  2  6  8  9  3]
 [ 4  5  5  7 10  9 10]
 [ 2  6  9  5  1  6  4]
 [ 5  8 10  0  7  2  6]]


[[ 7  4  8]
 [ 9  6  4]
 [ 5  2  2]
 [ 6  6  6]
 [ 7 10  9]
 [ 6  0  9]
 [ 2  7  9]]


In [22]:
print("El producto de las matrices A y B es \n" + str(np.dot(A, B)))

El producto de las matrices A y B es 
[[227 198 303]
 [168 170 212]
 [243 189 300]
 [284 268 365]
 [194 130 187]
 [230 200 227]]


## Ejercicio 4

Descomposicion qr

In [31]:
np.random.seed(8)  
A = np.random.randint(11, size=(6, 7))
print(A)

[[ 3  4  1  9  5 10  8]
 [ 3  8  0  5  1  3 10]
 [ 9  2  2  6  8  9  3]
 [ 4  5  5  7 10  9 10]
 [ 2  6  9  5  1  6  4]
 [ 5  8 10  0  7  2  6]]


In [32]:
q,r = np.linalg.qr(A)

In [36]:
print("La matriz q es" + "\n" + str(q) + "\n")
print("La matriz r es" + "\n"  + str(r))

La matriz q es
[[-0.25       -0.13836752 -0.25925066 -0.59221127  0.07808586 -0.70308744]
 [-0.25       -0.5408912  -0.70516854  0.22372789 -0.19333593  0.2454406 ]
 [-0.75        0.59120666 -0.06301014  0.05261494 -0.26705477  0.09958827]
 [-0.33333333 -0.15094638  0.10107022 -0.36513232  0.69086981  0.49524356]
 [-0.16666667 -0.42768141  0.50332551 -0.37444939 -0.59397064  0.20726988]
 [-0.41666667 -0.36478709  0.40988338  0.56826874  0.23474103 -0.38377358]]

La matriz r es
[[-12.         -10.5         -9.08333333 -11.16666667 -13.91666667
  -14.83333333 -13.25      ]
 [  0.          -9.93730346  -7.20768972  -3.59755543  -0.99373035
   -2.33966892 -10.15114416]
 [  0.           0.           8.7488436   -3.01304036   1.87770847
   -0.52575162  -3.83141654]
 [  0.           0.           0.          -8.32374545  -2.36430027
   -9.17374421  -4.08207464]
 [  0.           0.           0.           0.           6.01856993
    0.92084446   3.83142508]
 [  0.           0.           0.      

In [38]:
print("Comprobemos que la descomposición sea correcta con el producto de las matrices q y r: \n" + str(np.dot(q,r)))

Comprobemos que la descomposición sea correcta con el producto de las matrices q y r: 
[[3.00000000e+00 4.00000000e+00 1.00000000e+00 9.00000000e+00
  5.00000000e+00 1.00000000e+01 8.00000000e+00]
 [3.00000000e+00 8.00000000e+00 1.77635684e-15 5.00000000e+00
  1.00000000e+00 3.00000000e+00 1.00000000e+01]
 [9.00000000e+00 2.00000000e+00 2.00000000e+00 6.00000000e+00
  8.00000000e+00 9.00000000e+00 3.00000000e+00]
 [4.00000000e+00 5.00000000e+00 5.00000000e+00 7.00000000e+00
  1.00000000e+01 9.00000000e+00 1.00000000e+01]
 [2.00000000e+00 6.00000000e+00 9.00000000e+00 5.00000000e+00
  1.00000000e+00 6.00000000e+00 4.00000000e+00]
 [5.00000000e+00 8.00000000e+00 1.00000000e+01 8.88178420e-16
  7.00000000e+00 2.00000000e+00 6.00000000e+00]]
