# Tarea 5 - *Elementos de Numpy*

## Antonio Huerta Montellano

1. Supón que los nodos son los hashtags de todos los Twitter que se emiten en México en un cierto día. El peso de un enlace entre dos nodos de una red puede medir la proximidad entre esos dos nodos. ¿Cómo establecerías los pesos del enlace entre hashtags?

Primero, consideremos que intuitivamente un hastag tiene mucho peso si tiene mucho retwitts, y si estos a su vez tiene otros retwitts, el twitt fuente tendrá más relevancia entre más ramificaciones tenga.

Para establecer los pesos del enlace entre hastags podemos asociar un valor, $\rho_{1}$, por cada uno de los retwits directos del twit del que queremos establecer el peso. Luego, asociar otro valor, $\rho_{2}$, por cada retwitt que tengan los retwitts del punto anterior. Seguimos este proceso hasta el último retwitt $n$ en la cadena. Los valores $\rho_{i}$ son tales que $\rho_{i} > \rho_{j} \,\, \forall i>j$ con $i,j \in \{ 1,2,\cdots , n \}$ y el peso $\omega$ es

$$
\omega = \sum_{i=1}^{n} r_{i}\rho_{i}
$$

donde $r_{i}$ es la cantidad de valores $\rho_{i}$ que hay..

In [1]:
# Importación de librería
import numpy as np

2. Crea un arreglo con tres elementos y obtén con la función del seno() de Numpy los valores correspondientes, los cuales deben ser almacenados en otro vector para ser impresos. Realiza la misma operación, pero por un camino largo. Ejecuta un loop en el que cada uno de los elementos del arreglo inicial es transformado con el seno().

**Método directo:**

In [8]:
arr_1 = np.array([np.pi, np.pi/2, 3*np.pi/2])
print("El arreglo original es: " + str(arr_1))

El arreglo original es: [3.14159265 1.57079633 4.71238898]


In [10]:
sen_1 = np.sin(arr_1)
print("El arreglo con el seno del valor de cada entrada respectiva es: " + str(sen_1))

El arreglo con el seno del valor de cada entrada respectiva es: [ 1.2246468e-16  1.0000000e+00 -1.0000000e+00]


**Método largo:**

In [13]:
sen_2 = arr_1.copy()
for i in range(len(sen_1)):
    sen_2[i] = np.sin(arr_1[i])
print("El arreglo, por el método largo, con el seno del valor de cada entrada respectiva es: " + str(sen_2))

El arreglo, por el método largo, con el seno del valor de cada entrada respectiva es: [ 1.2246468e-16  1.0000000e+00 -1.0000000e+00]


3. Considera un polinomio de orden N. Escribe un programa con arreglos y métodos de Numpy. Implementa una función en la que se use el método cumprod(). Invoca a la función asignando un valor a la variable (x) y los coeficientes asociados del polinomio correspondiente (Ojo: si N = 2, debe haber tres coeficientes ya que hay un término constante). Estos coeficientes deben formar parte de un arreglo. Imprime el valor numérico de la función polinómica. Con el método de Numpy para la creación y evaluación de polinomios np.poly1d checa que el cálculo anterior sea el correcto.

In [71]:
def polinomio_evaluado(x,coeficientes):
    """
    Esta función toma los siguientes valores:
    x - Valor en el que será evaluado el polinomio
    coeficientes - Arreglo que contiene los coeficientes de mayor a menor
                   coeficiente de acuerdo a la potencia del exponente x,
                   incluyendo al intercepto.
    Dado un vector de coeficientes, se crea un vector auxiliar de la misma
    longitud, el cual será para obtener los valores de x por sus respectivas
    potencias. Una vez obtenidos el vector de valores de x a su respectiva
    potencia y en orden descendente, se multiplica por el vector de coeficien.
    tes. Por último, regresa la suma de todas las entradas de este vector.
    """
    
    valores = np.ones(len(coeficientes))*x # Se crea un arreglo auxiliar para la posterior creación del vector que contendrá los valores de x elevado a su respectiva potencia
    valores[0] = 1                         # Para el termino constante
    
    valores_pol = np.cumprod(valores)      # Obtener los valores de x a su respectiva potencia
    vector_valores = valores_pol[::-1]     # Ordenar de forma descendentes los valores del arreglo
    
    return np.sum(vector_valores*coeficientes) # Regresa la suma de todas las entradas del producto de los valores elevados a su respectiva potencia por los coeficientes

In [76]:
coef = np.array([5,4,3,2,3])
x = 2
polinomio_evaluado(x,coef)

131.0

**Comrpobación:**

In [73]:
p = np.poly1d([5,4,3,2,3])

Con esta opción se pueden apreciar a qué grado de $x$ pertence el coeficiente:

In [74]:
print(np.poly1d(p))

   4     3     2
5 x + 4 x + 3 x + 2 x + 3


In [75]:
p(2)

131

Se aprecia que se obtiene el mismo resultado, por lo que la función hecha en el punto anterior es correcta.

4. Crea una matriz (4 x 3) de números enteros generados aleatoriamente entre 0 y 10. Reemplaza los dos primeros vectores renglón con escalares = 7. Crea un nuevo arreglo (4 x 1) con puros unos y anéxalo con el método append() a la matriz anterior. Imprime cada uno de los resultados parciales que vas generando

Creemos la matriz $M\in\mathcal{M}_{4\times 3}(\mathbb{Z})$ con entradas de números aleatorios entre 0 y 10:

In [61]:
np.random.seed(8)  
M = np.random.randint(11, size=(4, 3))
print(M)

[[ 3  4  1]
 [ 9  5 10]
 [ 8  3  8]
 [ 0  5  1]]


Cambiemos cada entrada de los primeros dos renglones por el valor 7:

In [65]:
M[:2] = 7
print(M)

[[7 7 7]
 [7 7 7]
 [8 3 8]
 [0 5 1]]


Creemos una matriz con todas sus entradas igual a 1 de tamaño $4\times 1$:

In [67]:
arr_2 = np.ones((4,1))
print(arr_2)

[[1.]
 [1.]
 [1.]
 [1.]]


Anexemos por la derecha el vector anterior a la matriz $M$:

In [70]:
np.append(M,arr_2, axis=1)

array([[7., 7., 7., 1.],
       [7., 7., 7., 1.],
       [8., 3., 8., 1.],
       [0., 5., 1., 1.]])